/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 knot.gltf 
Author: mikedludlam (https://sketchfab.com/mikedludlam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/knotted-gem-c0efb7491be1453d8fb497ed31a79cdb
Title: Knotted Gem
*/

import React, { use } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/knot.gltf')
  const { actions } = useAnimations(animations, group)
  useFrame((state, delta)=>{
    group.current.rotation.y += delta * 0.2
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="dd93e4933cef411b86a95e5295846680fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="orb">
                  <mesh name="orb_OrbML_0" geometry={nodes.orb_OrbML_0.geometry} material={materials.OrbML} />
                </group>
                <group name="gem" scale={0.88}>
                  <mesh name="gem_GemSSG_0" geometry={nodes.gem_GemSSG_0.geometry} material={materials.GemSSG} />
                </group>
                <group name="knot_lo">
                  <mesh name="knot_lo_KnotSG_0" geometry={nodes.knot_lo_KnotSG_0.geometry} material={materials.KnotSG} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/knot.gltf')
